### PR TITLE
update version of testng to latest 6.9.12

### PR DESCRIPTION
**Pull request by missedone**

### CODE REVIEW

**Comment by juherr** [comment]
We should wait the avaibility on maven central before the merge.

**Comment by cbeust** [comment]
Nah, most people have JCenter in their build file these days...

**Comment by missedone** [comment]
so since 6.9.11, testng only available from JCenter?
there is no sort of synchronizer from JCenter to maven central?

**Comment by cbeust** [comment]
There is but Maven Central is giving me a hard time with PGP signing, so TestNG is on JCenter only for now.

**Comment by juherr** [comment]
@missedone Yes, it should be https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html

@cbeust Did you try https://blog.bintray.com/2013/08/06/fight-crime-with-gpg/ ?

> Bintray can now (optionally, only if you want it to!) manage your GPG keys and sign your Maven artifacts for you, so that you have proof about the authenticity of your goods.
All you’ve got to do, is generate your GPG key pair and associate it with a subject (be it your user or your evil organization):

**Pull request merged**
