### PR TITLE
Redirect to subrepo

### PR DESCRIPTION
**Pull request by juherr**
## Summary by CodeRabbit

- **Documentation**
	- Moved TestNG ant task documentation to its own repository.
	- Streamlined the installation process for TestNG for Eclipse, directing users to a documentation link for instructions.
	- Updated the TestNG Eclipse plug-in documentation, removing detailed instructions and images, and redirecting users to the plugin repository for information.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - Have you made a release of https://github.com/testng-team/testng-ant to Maven central yet? Shouldn't we be doing that?

**Comment by juherr** [comment]
That's a good point. I don't know if we need and if we need it before the testng release because it still contain classes.

**Comment by krmahadevan** [comment]
If we are going to be releasing testng v7.10.0 with all the ant classes removed then we should be providing the pre built jar for download. 

Since ant is an offline build tool, maybe we could just create a release and upload it back to github ?

**Comment by juherr** [comment]
I think we can merge the documentation PR as it only moves the documentation.
In a second time, I propose to release the ant extension if someone asks for it.
I'm not sure it will happen.

**Review by krmahadevan — APPROVED** [review]

**Pull request merged**
