### PR TITLE
Versions always up2date

### PR DESCRIPTION
**Pull request by juherr**

### CODE REVIEW

**Comment by cbeust** [comment]
I like the idea but I want to make sure this doesn't delay the display of the doc too much, I'll try this locally first.

**Comment by juherr** [comment]
Ping @cbeust I didn't find it slow but did you try on your side?

**Comment by cbeust** [comment]
Haven't tried it yet, no.

**Comment by Warfront1** [comment]
All manual tests were likely being conducted when the dependencies were performing properly.
In the case where our external calls/dependencies are down or are having poor performance we could run into issues.

Perhaps we could load it async, and have a default version. 
Although, it sort of feels weird adding all of these dependencies vs currently having none.

**Pull request closed without merging**
