### PR TITLE
Move javadoc to javadoc.io

### PR DESCRIPTION
**Pull request by juherr**
Related to https://github.com/cbeust/testng/issues/954 and https://github.com/cbeust/testng/issues/715

As javadoc.io doesn't allow object url without version, I created https://github.com/juherr/javadocio-proxy to fix the limitation. 

I think we can merge https://github.com/cbeust/testng/pull/977 too.

### CODE REVIEW

**Comment by cbeust** [comment]
I'm a bit concerned by this 

https://javadocio-proxy.herokuapp.com/org.testng/testng

URL.

Where does this go exactly? How does it get updated?

**Comment by juherr** [comment]
It is just custom http redirection. See  https://github.com/juherr/javadocio-proxy/blob/master/src/main/java/io/javadoc/JavadocIoProxy.java

I contacted javadoc.io owner months ago but I've no news from him.

**Comment by cbeust** [comment]
I'd rather manage the redirect myself then to avoid surprises. I could put one anywhere on testng.org, where would make the most sense?

**Comment by juherr** [comment]
You can do it by redirecting `/javadocs/`to http://www.javadoc.io/doc/org.testng/testng/

And with something like `RedirectMatch /javadocs/(.*)$ http://static.javadoc.io/org.testng/testng/6.9.10/$1` (but you will have to update the release number after each new release)
Or you can use my service for that with something like `RedirectMatch /javadocs/(.*)$ https://javadocio-proxy.herokuapp.com/org.testng/testng/$1`

**Comment by cbeust** [comment]
Done: go to http://testng.org and click on the JavaDoc link.

-- 
Cédric

**Comment by juherr** [comment]
http://testng.org/javadocs/ is working but not http://testng.org/javadocs/org/testng/ISuiteListener.html (which is linked in testng.org/doc/documentation-main.html)

**Comment by cbeust** [comment]
Indeed. I can't find a way to deep link into `javadoc.io` so far. Do you know what that URL would be?

**Comment by juherr** [comment]
http://static.javadoc.io/org.testng/testng/6.9.10/org/testng/ISuiteListener.html ?

**Comment by cbeust** [comment]
This works, but do you know if it's possible to get a link without the
version number?

Without that, I'd have to update all these links whenever a new version is
published, and in this case, I'd rather stick to linking to the docs on
testng.org...


-- 
Cédric

**Comment by juherr** [comment]
Nope, it is not possible for the moment. When I contacted the owner last summer, he told me he is working on it.
I tried to ping him in december without response.
That's why I made my own service which is doing the job ;)

**Comment by cbeust** [comment]
Ok, got it. Not sure what to do right now, going to think about it.

-- 
Cédric

**Comment by juherr** [comment]
If you want, you can deploy your own instance of my proxy service (on Heroku or whenever you prefer), I won't be upset ;)

**Comment by cbeust** [comment]
I'm more concerned by relying on another service than by who wrote the code
:-)

My thinking: the API barely changes these days so pointing to locally
generated Javadocs is pretty safe, even if those might be one version
behind. I think introducing a third party (well, two third parties:
javadoc.io and heroku) just for this is overkill.


-- 
Cédric

**Comment by cbeust** [comment]
I've restored the local javadocs for now.

-- 
Cédric

**Comment by juherr** [comment]
Ok, no problem ;)

**Pull request closed without merging**
