### PR TITLE
Cleaning up the DTD to be stricter with validation

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes https://github.com/testng-team/testng/issues/581

### CODE REVIEW

**Review by juherr — CHANGES_REQUESTED** [review]
The dtd is an artefact. You can modify it once published. We need to create a new minor version and treat it in the parser

**Comment by krmahadevan** [comment]
> The dtd is an artefact. You can modify it once published. We need to create a new minor version and treat it in the parser

You mean to say that we need to create a new file called `testng-1.1.dtd` and make the changes into that ? 

if so, then it will be used ONLY when a user updates 

* Old value: `<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">` to 
* New value: `<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.1.dtd">` 

in each of their suite files, which I doubt if anyone is ever going to be making. 

So what are we going to be achieving by publishing a new version?

I am curious to u'stand this aspect.

**Comment by krmahadevan** [comment]
@juherr - I have copied contents of `testng-1.0.dtd` into `testng-1.1.dtd` and made the required changes. Please check

**Comment by krmahadevan** [comment]
@juherr - I went through the TestNG codebase and here's what I found

* We try to load the dtd that is available in `src/main/resources`
* If that fails, then we fall back to loading the same dtd from `testng.org`

So I think that if we check-in the new dtd into testng codebase (which I have done in the other PR) then we should be good.

**Comment by krmahadevan** [comment]
> Do you confirm that the new dtd complains when used on a file with children under suite-file?

I tested this locally and this is what I see in IntelliJ

image

**Pull request merged**
